In [ ]:
! git clone https://github.com/wesm/pydata-book.git

In [1]:
v = list(range(1, 6))
v
2 * v

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [2]:
import numpy as np
v = np.arange(1, 6)
v
2 * v

array([ 2,  4,  6,  8, 10])

In [3]:
v= list(range(1,6))
v

[1, 2, 3, 4, 5]

In [4]:
2*v

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [5]:
import numpy as np
v= np.arange(1,6)
v

array([1, 2, 3, 4, 5])

In [6]:
2*v

array([ 2,  4,  6,  8, 10])

In [7]:
import numpy as np
a= np.arange(15)
print(a)
a=a.reshape(3,5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3, 5)
2
int64


In [9]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [12]:
b= np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23],
    [16,17,18,19,20]])
print(b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [15]:
a=np.arange(9).reshape(3,3)
print(a)
print(a[:2,1:],a[:2,1:].shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]] (2, 2)
